[build]
builder = "nixpacks"

[deploy]
startCommand = "cd agent-go && ./nerve-agent"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

